version: '3.7'
services:

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    restart: "always"
    ports:
      - ${REDIS_PORT}:6379

  beanstalkd:
    image: idcttech/beanstalkd:latest
    restart: "always"
    environment:
      - BINLOG=off
    ports:
      - ${BEANSTALKD_PORT}:11300

  mercure:
    image: dunglas/mercure
    hostname: publisher
    environment:
      DEBUG: false
      SERVER_NAME: ':80'
      MERCURE_TRANSPORT_URL: "local://local"
      MERCURE_PUBLISHER_JWT_KEY: 'Publish123'
      MERCURE_SUBSCRIBER_JWT_KEY: 'Subscribe123'
      MERCURE_EXTRA_DIRECTIVES: |-
          cors_origins "*"
          anonymous
          subscriptions
          dispatch_subscriptions
    ports:
      - ${MERCURE_PORT}:80
    volumes:
      - publisher:/data
    restart: "always"

  db:
    image: mariadb:11
    command: --max_allowed_packet=32505856 --innodb_log_file_size=512M --general_log=on --general_log_file=/tmp/mysql.log
    volumes:
       - database:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: devroot

  assets:
    hostname: assets
    image: nginx:mainline-alpine3.17-perl
    ports:
      - ${ASSETS_PORT}:80
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ${ASSETS_DIR}:/app/assets

volumes:
   redis: ~
   publisher: ~
   database: ~
