services:

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    restart: "always"
    ports:
      - ${REDIS_PORT}:6379

  redis2:
    image: redis:7-alpine
    volumes:
      - redis2:/data
    restart: "always"
    ports:
      - 7777:6379

  nats:
    build:
      context: nats
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - "${NATS_PORT}:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
      - ./nats/data:/data
      - ./nats/install:/opt/install
    # post_start:
    #   - command: /opt/install/init-nats.sh

  mercure:
    image: dunglas/mercure
    hostname: publisher
    environment:
      DEBUG: false
      SERVER_NAME: ':80'
      MERCURE_TRANSPORT_URL: "local://local"
      MERCURE_PUBLISHER_JWT_KEY: 'Publish123'
      MERCURE_SUBSCRIBER_JWT_KEY: 'Subscribe123'
      MERCURE_EXTRA_DIRECTIVES: |-
          cors_origins "*"
          anonymous
          subscriptions
          dispatch_subscriptions
    ports:
      - ${MERCURE_PORT}:80
    volumes:
      - publisher:/data
    restart: "always"

  db:
    image: mariadb:11
    command: --max_allowed_packet=32505856 --innodb_log_file_size=512M --general_log=on --general_log_file=/tmp/mysql.log
    volumes:
       - database:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: devroot

  assets:
    hostname: assets
    image: nginx:mainline-alpine3.20-perl
    ports:
      - ${ASSETS_PORT}:80
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ${ASSETS_DIR}:/app/assets

volumes:
   redis: ~
   redis2: ~
   publisher: ~
   database: ~
